#!/usr/bin/env bash
# Generates one UERANSIM UE config per subscriber.
# name  imsi-suffix  "dnn:sst:sd[,dnn:sst:sd]"
set -euo pipefail
cd "$(dirname "$0")"
K=465B5CE8B199B49FAA5F0A2EE238A6BC
OPC=E8ED289DEBA952E4283B54E88E6183CA

gen() {
  local name=$1 msin=$2 sess=$3
  local f="ue-$name.yaml"
  {
    echo "# UE $name — generated by gen_ues.sh"
    echo "supi: 'imsi-00101$msin'"
    echo "mcc: '001'"
    echo "mnc: '01'"
    echo "protectionScheme: 0          # null scheme SUCI (IMSI visible in captures)"
    echo "homeNetworkPublicKey: '5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650'"
    echo "homeNetworkPublicKeyId: 1"
    echo "routingIndicator: '0000'"
    echo "key: '$K'"
    echo "op: '$OPC'"
    echo "opType: 'OPC'"
    echo "amf: '8000'"
    echo "imei: '35693803564${msin: -4}'"
    echo "imeiSv: '43708161258${msin: -5}'"
    echo "gnbSearchList:"
    echo "  - 127.0.0.1"
    echo "uacAic: {mps: false, mcs: false}"
    echo "uacAcc: {normalClass: 0, class11: false, class12: false, class13: false, class14: false, class15: false}"
    echo "sessions:"
    IFS=, read -ra arr <<< "$sess"
    for s in "${arr[@]}"; do
      IFS=: read -r dnn sst sd <<< "$s"
      echo "  - type: 'IPv4'"
      echo "    apn: '$dnn'"
      echo "    slice: {sst: $sst, sd: 0x$sd}"
    done
    echo "configured-nssai:"
    for s in "${arr[@]}"; do
      IFS=: read -r dnn sst sd <<< "$s"
      echo "  - {sst: $sst, sd: 0x$sd}"
    done
    echo "default-nssai:"
    IFS=: read -r dnn sst sd <<< "${arr[0]}"
    echo "  - {sst: $sst, sd: 0x$sd}"
    echo "integrity: {IA1: true, IA2: true, IA3: true}"
    echo "ciphering: {EA1: true, EA2: true, EA3: true}"
    echo "integrityMaxRate: {uplink: 'full', downlink: 'full'}"
  } > "$f"
}

gen embb1  0000000001 internet:1:000001
gen embb2  0000000002 internet:1:000001
gen urllc1 0000000003 urllc:2:000002
gen miot1  0000000004 iot:3:000003
gen miot2  0000000005 iot:3:000003
gen multi  0000000006 internet:1:000001,urllc:2:000002
# negative test: subscribed only to eMBB but asks for URLLC
gen badslice 0000000007 urllc:2:000002
echo "generated: $(ls ue-*.yaml | tr '\n' ' ')"
